### ISSUE TITLE
ClassCastException when arangodb.acquireHostList=true

### ISSUE THREAD

**Issue by rashtao** [arangodb/arangodb-java-driver-async#21]
When `arangodb.acquireHostList=true` is set `com.arangodb.ArangoDBTest` fails with the following error:

```

java.lang.ClassCastException: class com.arangodb.internal.velocystream.VstConnectionAsync cannot be cast to class com.arangodb.internal.velocystream.internal.VstConnectionSync (com.arangodb.internal.velocystream.VstConnectionAsync and com.arangodb.internal.velocystream.internal.VstConnectionSync are in unnamed module of loader 'app')

	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:132)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:79)
	at com.arangodb.internal.net.ExtendedHostResolver.resolveFromServer(ExtendedHostResolver.java:139)
	at com.arangodb.internal.net.ExtendedHostResolver.resolve(ExtendedHostResolver.java:91)
	at com.arangodb.internal.net.FallbackHostHandler.confirm(FallbackHostHandler.java:75)
	at com.arangodb.internal.net.DirtyReadHostHandler.confirm(DirtyReadHostHandler.java:73)
	at com.arangodb.internal.velocystream.VstCommunication.connect(VstCommunication.java:100)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:131)
	at com.arangodb.internal.ArangoExecutorAsync.execute(ArangoExecutorAsync.java:65)
	at com.arangodb.internal.ArangoExecutorAsync.execute(ArangoExecutorAsync.java:57)
	at com.arangodb.internal.ArangoDBAsyncImpl.createDatabase(ArangoDBAsyncImpl.java:100)
	at com.arangodb.ArangoDBTest.createDatabase(ArangoDBTest.java:84)
	...


```

**Comment by wajda** [comment]
Any update on this please?

**Comment by rashtao** [comment]
I haven't worked on this yet.
From a first look to the related code, it seems to me a bit hard to implement without blocking the thread, because of the way it has been designed (VstConnectionAsync delegating VstConnectionSync). If you can figure out an easy way to fix it, feel free to submit a PR!
Otherwise, as workaround I suggest you adding all the hosts in the configuration. 

Also consider that we are currently working on a rewrite of the driver based on reactive streams, which will supersede the asynchronous driver. You can follow the development here: https://github.com/arangodb/arangodb-java-driver/tree/next

**Comment by wajda** [comment]
Thanks for the update @rashtao
I've realized that in my case this error only happens on the first call on the application start time. The second time I call the same method it works. Will retest it in a new driver, but meantime this is a workaround that works for me:
```scala
try {
  arangoDatabase.getInfo.get()
} catch {
  // The first call fails with a CCE due to a bug in ArangoDB Java Driver (arangodb/arangodb-java-driver-async#21)
  case ee: ExecutionException if ee.getCause.isInstanceOf[ClassCastException] =>
    arangoDatabase.getInfo.get()
}
```

**Comment by rashtao** [comment]
Fixed by https://github.com/arangodb/arangodb-java-driver/pull/378
